### PR TITLE
Support Auto-Discovery

### PR DESCRIPTION
**Pull request by m1guelpf**
This will make the package work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5

### CODE REVIEW

**Comment by Omranic** [comment]
@GrahamCampbell can we merge this please..

**Comment by GrahamCampbell** [comment]
I'm still in two minds if I want to support auto-discovery. Seems very odd that requiring a package should have side effects. Any how, unfortunately, all these PRs have merge conflicts, so can't be merged.

**Comment by Omranic** [comment]
In real need for this, and I don't think it has unexpressed side effects. If you agree, I can open a new clean PR, ..?

**Comment by m1guelpf** [comment]
@GrahamCampbell Solved merge conflicts

**Comment by Omranic** [comment]
@m1guelpf nice, thanks 🙏 hope this find its way to **master** branch

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Pull request merged**
