### PR TITLE
Laravel 10 support

### PR DESCRIPTION
**Pull request by stefnats**
This is a simple PR for upgrading to Laravel 10.
I hope that i didn't miss anything :)

### CODE REVIEW

**Comment by mrailton** [comment]
👍🏻 Was coming here to add this, thanks for doing it @stefnats, hopefully Graham has time soon to accept and release

**Comment by Quadrubo** [comment]
Hey, you made an error in your composer.json file. There are too many quotation marks.

Your composer.json
```json
...
        "illuminate/contracts": "^8.75 || ^9.0" || ^10.0",
        "illuminate/filesystem": "^8.75 || ^9.0 || ^10.0"",
        "illuminate/support": "^8.75 || ^9.0 || ^10.0"",
        "illuminate/view": "^8.75 || ^9.0 || ^10.0"",
...
```

The right composer.json
```json
...
        "illuminate/contracts": "^8.75 || ^9.0 || ^10.0",
        "illuminate/filesystem": "^8.75 || ^9.0 || ^10.0",
        "illuminate/support": "^8.75 || ^9.0 || ^10.0",
        "illuminate/view": "^8.75 || ^9.0 || ^10.0",
...
```

**Comment by Quadrubo** [comment]
@stefnats I opened a pull request on your fork so I don't have to open a second pr on this repo

**Comment by stefnats** [comment]
@Quadrubo ah thanks, sorry, it was too early this morning :)

**Comment by ultrono** [comment]
For the impatient people such as myself, I've made a quick fork that includes this PR. All tests are passing.

`composer require ultrono/markdown`

See https://github.com/ultrono/Laravel-Markdown

When this PR is merged in the main repository I'll delete my fork to avoid confusion.

**Comment by jorenvh** [comment]
@GrahamCampbell any chance this can be merged? Currently blocks upgrades to Laravel 10.

I've worked around it with a fork and am currently using that. But I rather switch that to the original package before pushing to production :)

**Comment by GrahamCampbell** [comment]
Thanks for making a start here, though there are quite a few missing things here, such as updating the readme, and the tests are currently failing. I will handle the upgrade myself, shortly. In the meanwhile, [Sponsoring me](https://github.com/sponsors/GrahamCampbell) is a great way to support this project, and better enable me to perform these upgrades in a timely manor. I maintain or co-maintain upwards of 100 OSS repos. 💻

**Comment by GrahamCampbell** [comment]
v15.0.0 has now been released, with PHP 8.2 and Laravel 10 support.

**Comment by ultrono** [comment]
> Thanks for making a start here, though there are quite a few missing things here, such as updating the readme, and the tests are currently failing. I will handle the upgrade myself, shortly. In the meanwhile, [Sponsoring me](https://github.com/sponsors/GrahamCampbell) is a great way to support this project, and better enable me to perform these upgrades in a timely manor. I maintain or co-maintain upwards of 100 OSS repos. 💻

Yep it was done very quickly as I needed it for an upgrade. All tests passed on my fork with PHP 8.1 and Laravel.

**Pull request closed without merging**
