### PR TITLE
`::class` notation

### PR DESCRIPTION
**Pull request by younes0**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No thanks.

**Comment by tuwannu** [comment]
@GrahamCampbell Any reason why you prefer string over `::class`? `::class` allows static analysis to detect missing classes rather than spotting it at runtime and so I usually would prefer it over strings.

**Comment by GrahamCampbell** [comment]
I just want to change the readme to just give the class name, without suggesting a syntax to use. Will update all my readmes at somepoint in the future, but it's not a big priority. :)

**Comment by tuwannu** [comment]
Thanks for the clarification! :)

**Pull request closed without merging**
