### PR TITLE
Add option to load/add custom Parsers and Renderers to CustomMark

### PR DESCRIPTION
**Pull request by lucasmezencio**
Maybe the option 'parsers' may not be the best name, but I did not realize any other name for this. :disappointed:

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You should add these via an extension.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Emoji is an example if you need one.

**Comment by GrahamCampbell** [comment]
What I'm saying is, this is already possible, in a unified way. ;)

**Comment by pedrommone** [comment]
:+1: for the PR, its a better way in my opinion.

**Comment by lucasmezencio** [comment]
Can you help me, so? The example you sent to me is very nice, but it uses a Renderer that is 'default' on CommonMark.
In my case, I have created a custom Element, Parser and Renderer, but I can not add it via Extension.
I am receiving the following error:
`Unable to find corresponding renderer for inline type Hermes\Picture`

Here is my Extension:
```php
<?php

namespace Hermes;

use League\CommonMark\Extension\Extension;

class PictureExtension extends Extension
{
    protected $parser;
    protected $renderer;

    public function __construct(PictureParser $parser, PictureRenderer $renderer)
    {
        $this->parser = $parser;
        $this->renderer = $renderer;
    }

    public function getInlineParsers()
    {
        return [
            $this->parser,
        ];
    }

    public function getInlineRenderers()
    {
        return [
            $this->renderer,
        ];
    }
}
```

**Comment by GrahamCampbell** [comment]
> :+1: for the PR, its a better way in my opinion.

It's not really an option. We already have a standard way.

**Comment by lucasmezencio** [comment]
Sorry dude. My bad. Thanks! :)

**Pull request closed without merging**
