### PR TITLE
Markdown extensions

### PR DESCRIPTION
**Pull request by haleksandre**
Add the possibility of registering extensions via the commonmark environment's addExtension method.

Here's a few extension available:
- [CommonMark Attributes Extension](https://github.com/webuni/commonmark-attributes-extension)
- [CommonMark Table Extension](https://github.com/webuni/commonmark-table-extension)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It's already possible to add extensions.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Emoji is an example.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Emoji/blob/master/src/EmojiServiceProvider.php#L88

**Comment by haleksandre** [comment]
Yes, it's possible to add extensions if you create a Laravel package.  What I'm suggesting is extension that make use of CommonMark's addExtension() which make it easier to add non-Laravel package such as:
- [CommonMark Attributes Extension](https://github.com/webuni/commonmark-attributes-extension)
- [CommonMark Table Extension](https://github.com/webuni/commonmark-table-extension)

**Comment by GrahamCampbell** [comment]
You don't need to create a laravel package at all. You can just add a very small amount of code in your app service provider. This is no different to adding configuration in a config file at the end of the day, and is way more configurable and customisable.

**Comment by salarmehr** [comment]
@haleksandre +1
If somebody seek more flexibility he can use app service provider, if not he can add extension fast. 
@GrahamCampbell At least please add some note to readme.md regarding extensions.

**Comment by haleksandre** [comment]
@salarmehr I have created my own markdown package which let you extend CommonMark via the configuration file as well as additional features.  For more info visit the package repo at https://github.com/haleks/laravel-markdown

**Pull request closed without merging**
