### PR TITLE
Adding an Extension Example into Readme

### PR DESCRIPTION
**Pull request by tevfik6**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but I'm not sure if this is a bit overkill. Doesn't the docs website already have a full extension example over at the league?

**Comment by tevfik6** [comment]
It's all up to you. If I had problem build it, some other will do as well. 
You are the owner of the repo mate. I propose it, you decide merge or not :)

Tev.

**Comment by GrahamCampbell** [comment]
Maybe a lighter example would be better?

**Comment by GrahamCampbell** [comment]
Like, skip out the `CustomHeadingRenderer` stuff since that's got nothing to do with this package.

**Comment by tevfik6** [comment]
Well, you can remove it. But don't know how would you show/explain __construct of Extension file.
Maybe we can change it like;
```php
public function __construct(YourCustomRendererClass $renderer)
```

From my point of view providing a full example would be better to kick start even for people who recently started to develop in laravel. 

It's up to you. :) I don't mind changing things in it. I'll keep them in my own fork.

**Comment by GrahamCampbell** [comment]
Hmm, I'll think about it. Sorry if I don't get to you for a while. I'm insanely busy right now. Thanks for the PR though!

**Comment by GrahamCampbell** [comment]
Merging, but will shorten. :)

**Comment by GrahamCampbell** [comment]
Thanks!

**Pull request merged**
